name: Build in multiple platforms

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build Update
        run: |
          yarn --frozen-lockfile
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: "Build ${{ matrix.os }}"
          path: |
            build/Genshin*zip
            build/Genshin*deb
